[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
proxy_mode = True
; Keep True only for first database creation. Change to False after setup.
list_db = True
; For this tiny VPS, start single-process first. Tune later after measuring.
workers = 0
max_cron_threads = 1
